
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

# [colors.search.footer.bar]
# background = "#434c5e"
# vforeground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor.style]
blinking = "Always"
shape = "Block"

[debug]
persistent_logging = false

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 15
y = 15
